swagger: '2.0'

info:
  version: 1.0.0
  title: DistinctAI - CVX
  description: |
    **Errors**

    Uses conventional HTTP response codes to indicate success or failure. In general, codes in the `2xx` range indicate success. Codes in the `4xx` range indicate an error (e.g. required parameters, failed request etc.). Codes int he `5xx` range indicate a server error occurred.
  
  contact:
    name: DistinctAI
    email: developers@distinct.ai
  
  license:
    name: Proprietary

host: dev-api.distinct.ai
basePath: /cvx
schemes:
  - http
  - https

securityDefinitions:
  authToken:
    type: apiKey
    name: x-auth-token
    in: header

tags:
  - name: user
    description: User related endpoints
  - name: public
    description: Publicly available endpoints

paths:
  /file:
    get:
      tags:
        - user
      security:
        - authToken: []
      summary: Get user's CV
      produces:
        - application/json
      responses:
        200:
          description: Operation successful
          schema:
            $ref: '#/definitions/CvFileDto'

    post:
      tags:
        - user
      security:
        - authToken: []
      operationId: addCvFile
      summary: Add a user's CV
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          description: Presigned URL request body
          schema:
            $ref: '#/definitions/CvFileDto'
      responses:
        200:
          description: Operation successful
          schema:
            $ref: '#/definitions/CvFileDto'

definitions:
  CvFileDto:
    type: object
    properties:
      id:
        type: string
        readOnly: true
        format: uuid
      fileKey:
        type: string
      fileName:
        type: string
        readOnly: true
      originalFileName:
        type: string
      url:
        type: string
      content:
        type: object
        readOnly: true
        properties: 
          html:
            type: string
          css:
            type: string

  CvUserDto:
    type: object
