swagger: '2.0'

info:
  version: 1.0.0
  title: DistinctAI - Files
  description: |
    **Errors**

    Uses conventional HTTP response codes to indicate success or failure. In general, codes in the `2xx` range indicate success. Codes in the `4xx` range indicate an error (e.g. required parameters, failed request etc.). Codes int he `5xx` range indicate a server error occurred.
  
  contact:
    name: DistinctAI
    email: developers@distinct.ai
  
  license:
    name: Proprietary

host: dev-api.distinct.ai
basePath: /files
schemes:
  - http
  - https

securityDefinitions:
  authToken:
    type: apiKey
    name: x-auth-token
    in: header

tags:
  - name: user
    description: User related endpoints
  - name: public
    description: Publicly available endpoints

paths:
  /me/upload/generate-presigned-url:
    post:
      tags:
        - user
      security:
        - authToken: []
      summary: Generate a file presigned url
      description: |
        Generate upload presigned url for file to be uploaded to amazon s3 bucket
      operationId: generateFilePresignedUrl
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          description: Presigned URL request body
          schema:
            $ref: '#/definitions/PresignedUrlDto'
      responses:
        200:
          description: Operation successful
          schema:
            $ref: '#/definitions/PresignedUrlGeneratedDto'

definitions:
  PresignedUrlDto:
    type: object
    required:
      - contentType
    properties:
      contentType:
        type: string
        example: image/png
      uploadType:
        type: string
        enum:
          - CV
          - PHOTOS
          - PROCTOR

  PresignedUrlGeneratedDto:
    type: object
    properties:
      success:
        type: boolean
        example: true
      message:
        type: string
        example: AWS SDK S3 Pre-signed urls generated successfully
      signedUrl:
        type: string
      fileKey:
        type: string
      fileUrl:
        type: string

  FileDto:
    type: object
    properties: 
      fileKey:
        type: string
      fileSize:
        type: string
      lastModified:
        type: string
        format: date-time
      contentType:
        type: string
