swagger: '2.0'

info:
  version: 1.0.0
  title: DistinctAI - Jobs
  description: |
    **Errors**

    Uses conventional HTTP response codes to indicate success or failure. In general, codes in the `2xx` range indicate success. Codes in the `4xx` range indicate an error (e.g. required parameters, failed request etc.). Codes int he `5xx` range indicate a server error occurred.
  
  contact:
    name: DistinctAI
    email: developers@distinct.ai
  
  license:
    name: Proprietary

host: dev-api.distinct.ai
basePath: /jobs
schemes:
  - http
  - https

securityDefinitions:
  authToken:
    type: apiKey
    name: x-auth-token
    in: header

tags:
  - name: user
    description: User related endpoints
  - name: public
    description: Publicly available endpoints

paths:
  /create:
    post:
      tags:
        - user
      security:
        - authToken: []
      operationId: createJob
      summary: Create a job
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '_common.yaml#/definitions/JobDto'
      responses:
        200:
          description: Request successful
          schema:
            $ref: '_common.yaml#/definitions/JobDto'

  /all:
    get:
      tags:
        - user
      security:
        - authToken: []
      summary: Get list of jobs
      operationId: getJobsList
      produces:
        - application/json
      parameters:
        - in: query
          name: status
          required: false
          type: string
        - in: query
          name: text
          required: false
          type: string
        - in: query
          name: salaryFrom
          required: false
          type: string
        - in: query
          name: salaryTo
          required: false
          type: string
        - in: query
          name: type
          required: false
          type: string
      responses:
        200:
          description: Request successful
          schema:
            $ref: '#/definitions/JobListDto'

  /all/{id}:
    parameters:
      - in: path
        name: id
        description: Job Id
        required: true
        type: string
        format: uuid

    post:
      tags:
        - user
      security:
        - authToken: []
      operationId: publishJob
      summary: Publish a job
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/JobStatusRequestDto'
      responses:
        200:
          description: Request successful
          schema:
            $ref: '_common.yaml#/definitions/JobDto'

    get:
      tags:
        - user
      security:
        - authToken: []
      summary: Get job by ID
      operationId: getJobByID
      produces:
        - application/json
      responses:
        200:
          description: Request successful
          schema:
            $ref: '_common.yaml#/definitions/JobDto'

    patch:
      tags:
        - user
      security:
        - authToken: []
      operationId: updateJob
      summary: Update a job by ID
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '_common.yaml#/definitions/JobDto'
      responses:
        200:
          description: Request successful
          schema:
            $ref: '_common.yaml#/definitions/JobDto'

    delete:
      tags:
        - user
      security:
        - authToken: []
      operationId: deleteJob
      summary: Delete a job
      produces:
        - application/json
      responses:
        200:
          description: Request successful
          schema:
            $ref: '_common.yaml#/definitions/StatusDto'

definitions:
  JobStatusRequestDto:
    type: object
    properties: 
      status:
        type: string
        enum:
          - PUBLISH
          - CLOSE

  JobListDto:
    allOf:
      - $ref: '_common.yaml#/definitions/Paging'
      - properties:
          records:
            type: array
            items:
              $ref: '_common.yaml#/definitions/JobDto'
